apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-lancamentos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio-lancamentos-app
  template:
    metadata:
      labels:
        app: desafio-lancamentos-app
    spec:
      containers:
        - name: desafio-lancamentos-app
          image: desafio-lancamentos-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: lancamento-service
spec:
  type: NodePort
  selector:
    app: desafio-lancamentos-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30005
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-desafio
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: lancamentos.desafio.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lancamento-service
                port:
                  number: 80  